name: Create Release and Update Repository

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    uses: Catphinaud/DalamudPlugins/.github/workflows/reusable_create_broken_plugin.yml@main
    with:
      internal_name: OhHeyFork
      solution_name: OhHeyFork
      build_configuration: Release
      personal_plugin_repo: Catphinaud/DalamudPlugins
      personal_plugin_repo_branch: main
      plugin_dir: src/OhHeyFork
      release_name: OhHeyFork
    secrets: inherit
